FROM maven:3.9-eclipse-temurin-21
WORKDIR /app

# Cache dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy source code
COPY src ./src

EXPOSE 8080

# Run Spring Boot in dev mode using Maven
CMD ["mvn", "spring-boot:run"]